name: Purge JSDelivr Cache

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  purge_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Purge JSDelivr Cache for all assets
        run: |
          # Iterate over all files in src/assets and purge them
          for file in $(find src/assets -type f); do
            url="https://purge.jsdelivr.net/gh/Pixoform2025/Pixoform@latest/$file"
            echo "Purging: $url"
            curl -X GET "$url"
          done
